First attempt to include uhttp library with azure-iot-sdk build
The uhttp library is not built unless we avoid specifying
use_installed_dependencies:BOOL=ON in the
[EXTRA_OECMAKE](https://github.com/intel-iot-devkit/meta-iot-cloud/blob/warrior/recipes-azure/azure-iot-sdk-c/azure-iot-sdk-c.inc#L24).

This patch modifies to support building without
use_installed_dependencies=ON, and building uhttp library.

However, there is an issue with the resulting build which is:
```
ERROR: azure-app-1.0+gitAUTOINC+eb9f7e087d-r0 do_prepare_recipe_sysroot: The file /usr/lib/libaziotsharedutil.a is installed by both azure-c-shared-utility and azure-iot-sdk-c, aborting
```